ManejadorDePresupuestos/ManejadorDePresupuestos/Models/PaginacionViewModel.cs
namespace ManejadorDePresupuestos.Models
{
    public class PaginacionViewModel
    {
        public int Pagina { get; set; } = 1;
        private int recordsPorPagina = 10;
        private readonly int maxRecordForPages = 50;

        public int RecordsPorPagina
        {
            get{
                return recordsPorPagina;
            }
            set {

                recordsPorPagina = value > maxRecordForPages ? maxRecordForPages : value;
            }
        }

        public int RecordASaltar => recordsPorPagina * (Pagina - 1);

    }
}

ManejadorDePresupuestos/ManejadorDePresupuestos/Models/ReporteTransaccionesDetalladas.cs
using System.Collections;

namespace ManejadorDePresupuestos.Models
{
    public class ReporteTransaccionesDetalladas
    {
        public DateTime FechaInicio { get; set; }
        public DateTime FechaFin { get; set; }
        public IEnumerable<TransaccionesPorFecha> TransaccionesAgrupadas { get; set; }
        public decimal BalanceDepositos => TransaccionesAgrupadas.Sum(z  => z.BalanceDepositos);
        public decimal BalanceRetiros => TransaccionesAgrupadas.Sum(z => z.BalanceRetiros);

        public decimal Total  => BalanceDepositos - BalanceRetiros;

        public class TransaccionesPorFecha
        {
            public DateTime fechaTransaccion { get; set; }
            public IEnumerable<Transaccion> Transacciones { get; set; }
            public decimal BalanceDepositos => 
                Transacciones.Where(x => x.TipoOperacionID == TipoOperacion.Ingreso)
                .Sum(x => x.Monto);
            public decimal BalanceRetiros =>
                Transacciones.Where(x => x.TipoOperacionID == TipoOperacion.Gasto)
                .Sum(x => x.Monto);
                    }

    }
}

ManejadorDePresupuestos/ManejadorDePresupuestos/Models/ResumenMontosViewModel.cs
namespace ManejadorDePresupuestos.Models
{
    public class ResumenMontosViewModel
    {
        public decimal Ingresos { get; set; }
        public decimal Gastos { get; set; }
        public decimal Total { get; set; }
    }
}

ManejadorDePresupuestos/ManejadorDePresupuestos/Controllers/CuentasController.cs
using AutoMapper;
using ManejadorDePresupuestos.Models;
using ManejadorDePresupuestos.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ManejadorDePresupuestos.Controllers
{
    public class CuentasController : Controller
    {
        private readonly IRepositorioTipoCuentas repositorioTipoCuentas;
        private readonly IServicioUsuarios servicioUsuarios;
        private readonly IRepositorioCuentas repositorioCuentas;
        private readonly IMapper mapper;
        private readonly IRepositorioTransacciones repositorioTransacciones;
        private readonly IServicioReportes servicioReportes;

        public CuentasController(IRepositorioTipoCuentas repositorioTipoCuentas, IServicioUsuarios servicioUsuarios,IRepositorioCuentas repositorioCuentas,IMapper mapper, IRepositorioTransacciones repositorioTransacciones, IServicioReportes servicioReportes)
        {
            this.repositorioTipoCuentas = repositorioTipoCuentas;
            this.servicioUsuarios = servicioUsuarios;
            this.repositorioCuentas = repositorioCuentas;
            this.mapper = mapper;
            this.repositorioTransacciones = repositorioTransacciones;
            this.servicioReportes = servicioReportes;
        }

        [HttpGet]
        public async Task< IActionResult> Crear()
        {
            var usuarioID = servicioUsuarios.ObtenerUsuarioID();
            var modelo = new CuentaCreacionViewModel();
            modelo.TiposCuentas = await ObtenerTiposCuentas(usuarioID);

            
            return View(modelo);
        }

        public async Task<IActionResult> Detalle(int id,int mes,int ano)
        {
            var usuarioID = servicioUsuarios.ObtenerUsuarioID();
            var cuenta = await repositorioCuentas.ObtenerCuentaPorID(id, usuarioID);

            if(cuenta == null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            ViewBag.Cuenta = cuenta.Nombre;

            var modelo = await servicioReportes.ObtenerTransaccionesDetalladasPorCuenta(usuarioID, id, mes, ano, ViewBag);

          
            return View(modelo);

        }


        [HttpPost]
        public async Task<IActionResult>Crear(CuentaCreacionViewModel modelo)
        {
            var usuarioID = servicioUsuarios.ObtenerUsuarioID();
            var tipoCuenta = await repositorioTipoCuentas.ObtenerPorID(modelo.TipoCuentaID,usuarioID);

            if(tipoCuenta == null) { return RedirectToAction("NoEncontrado", "Home"); }

            if(!ModelState.IsValid) {

                modelo.TiposCuentas = await ObtenerTiposCuentas(usuarioID);
                return View(modelo);
            }

            await repositorioCuentas.Crear(modelo);
            return RedirectToAction("Index");
        }

        private async Task<IEnumerable<SelectListItem>> ObtenerTiposCuentas(int usuarioID)
        {
            var tipoCuentas = await repositorioTipoCuentas.Obtener(usuarioID);
            return tipoCuentas.Select(x => new SelectListItem(x.Nombre, x.ID.ToString()));
        } 

        public async Task<IActionResult> Index()
        {
            var usuarioID = servicioUsuarios.ObtenerUsuarioID();
            var cuentasConTipoCuenta = await repositorioCuentas.Buscar(usuarioID);

            var modelo = cuentasConTipoCuenta
                .GroupBy(x => x.TipoCuenta)
                .Select(grupo => new IndiceCuentasViewModel
                {
                    TipoCuenta = grupo.Key,
                    Cuentas = grupo.AsEnumerable()
                }).ToList();

            return View(modelo);
        }

        public async Task<IActionResult> Editar(int id)
        {
            var usuarioID = servicioUsuarios.ObtenerUsuarioID();
            var cuentaAEditar = await repositorioCuentas.ObtenerCuentaPorID(id,usuarioID);

            if(cuentaAEditar == null) { return RedirectToAction("NoEncontrado","Home"); }

            var modelo = mapper.Map<CuentaCreacionViewModel>(cuentaAEditar);

            modelo.TiposCuentas = await ObtenerTiposCuentas(usuarioID);

            return View(modelo);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(CuentaCreacionViewModel cuentaAEditar)
        {
            var usuarioID = servicioUsuarios.ObtenerUsuarioID();
            var cuenta = await repositorioCuentas.ObtenerCuentaPorID(cuentaAEditar.ID, usuarioID);
            if(cuenta == null) { return RedirectToAction("NoEncontrado", "Home"); }

            var tipoCuenta = await repositorioTipoCuentas.ObtenerPorID(cuenta.ID, usuarioID);
            if (tipoCuenta == null) { return RedirectToAction("NoEncontrado", "Home"); }

            await repositorioCuentas.Actualizar(cuentaAEditar);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Borrar(int id)
        {
            var usuarioID = servicioUsuarios.ObtenerUsuarioID();
            var cuenta = await repositorioCuentas.ObtenerCuentaPorID(id, usuarioID);
            if (cuenta == null) { return RedirectToAction("NoEncontrado", "Home"); }

            return View(cuenta);
        }

        [HttpPost]
        public async Task<IActionResult> BorrarCuenta(int id)
        {
            var usuarioID = servicioUsuarios.ObtenerUsuarioID();
            var cuenta = await repositorioCuentas.ObtenerCuentaPorID(id, usuarioID);
            if (cuenta == null) { return RedirectToAction("NoEncontrado", "Home"); }

            await repositorioCuentas.Borrar(id);

            return RedirectToAction("Index");
        }

    }
}

ManejadorDePresupuestos/ManejadorDePresupuestos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ManejadorDePresupuestos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ManejadorDePresupuestos.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/lib/full-calendar/main.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Transacciones" asp-action="Index">ManejadorDePresupuestos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Transacciones" asp-action="Index">Transacciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="TipoCuentas" asp-action="Index">Tipos Cuentas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cuentas" asp-action="Index">Cuentas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Categorias" asp-action="Index">Categorias</a>
                        </li>
                    </ul>
                    <partial name="_LinksLogin" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ManejadorDePresupuestos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ManejadorDePresupuestos/ManejadorDePresupuestos/Views/Shared/_LinksLogin.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Usuario> SingInManager

<ul class="navbar-bar nav">
    @if (SingInManager.IsSignedIn(User))
    {
        <li class="nav-item ">
            <span class="nav-link text-black">Hola, @User.Identity.Name</span>
        </li>
        <li class="nav-item">
            <form class="form-inline" asp-action="logout" asp-controller="usuarios">
                <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
            </form>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="usuarios" asp-action="Registro">Registro</a>
        </li>
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="usuarios" asp-action="Login">Login</a>
        </li>
    }
</ul>

ManejadorDePresupuestos/ManejadorDePresupuestos/Views/Shared/_NavegarPorMeses.cshtml
@model DateTime

<h4>
    <a asp-route-mes="@ViewBag.mesAnterior" asp-route-ano="@ViewBag.anoAnterior"
       class="btn btn-secondary"><i class="bi-chevron-left"></i></a>
    @Model.ToString("MMM") - @Model.Year

    <a asp-route-mes="@ViewBag.mesPosterior" asp-route-ano="@ViewBag.anoPosterior"
       class="btn btn-secondary"><i class="bi-chevron-right"></i></a>
</h4>

ManejadorDePresupuestos/ManejadorDePresupuestos/Views/Shared/_Paginacion.cshtml
@model PaginacionRespuesta

@{
    var plantillaLink = string.Concat(Model.BaseURL, "?pagina={0}&recordsPorPagina={1}");
    var activarBotonAnterior = Model.Pagina > 1;
    var activarBotonSiguiente = Model.Pagina < Model.CantidadTotalDePaginas;
}

<nav>
    <ul class="pagination">
        @if (activarBotonAnterior)
        {
        <li class="page-item">
                <a class="page-link" href="@string.Format(plantillaLink,Model.Pagina - 1,Model.RecordsPorPagina)">
                    Anterior
                </a>
            </li>
        }
        else
        {
            <span class="page-link disabled">Anterior</span>
        }
        @for (int pagina = 1; pagina <= Model.CantidadTotalDePaginas; pagina++)
        {
            <li class="page-item @(pagina == Model.Pagina ? "active":null)">
                <a class="page-link" href="@string.Format(plantillaLink,pagina,Model.RecordsPorPagina)">
                    @pagina
                </a>
            </li>
        }
        @if (activarBotonSiguiente)
        {
        <li class="page-item ">
            <a class="page-link" href="@string.Format(plantillaLink,Model.Pagina + 1,Model.RecordsPorPagina)">
                Siguiente
            </a>
            </li>
        }
        else
            {
                <span class="page-link disabled">Siguiente</span>
            }
            </ul>
</nav>

ManejadorDePresupuestos/ManejadorDePresupuestos/Views/Shared/_ReporteTransaccionesDetalladas.cshtml
@model ReporteTransaccionesDetalladas

@{
    var resumenMontos = new ResumenMontosViewModel()
            {
                Ingresos = Model.BalanceDepositos,
                Gastos = Model.BalanceRetiros,
                Total = Model.Total,
            };
}

<partial name="_NavegarPorMeses" model="@Model.FechaInicio"/>
<partial name="_ResumenMontos" model="@resumenMontos" />

@if (Model.TransaccionesAgrupadas.Count() == 0)
{
    <h3>No hay datos para mostrar</h3>
}
else
{
    <table class="table">
        <tbody>
            @foreach (var transaccionAgrupada in Model.TransaccionesAgrupadas)
            {

                <tr>
                    <td colspan="3">
                        @transaccionAgrupada.fechaTransaccion.Day
                        <span class="badge bg-secondary">@transaccionAgrupada.fechaTransaccion.ToString("ddd")</span>
                    </td>
                    <td>
                        @transaccionAgrupada.BalanceDepositos
                    </td>
                    <td>
                        @transaccionAgrupada.BalanceRetiros
                    </td>

                </tr>
                @foreach (var transaccionesDia in transaccionAgrupada.Transacciones)
                {
                    <tr style="vertical-align:middle">
                        <td>
                            <a asp-controller="transacciones" asp-action="Editar" asp-route-id="@transaccionesDia.Id" asp-route-urlRetorno="@ViewBag.urlRetorno">
                                <i class="bi-pencil"></i>
                            </a>
                        </td>
                        <td>@transaccionesDia.Categoria</td>
                        <td>@transaccionesDia.Cuenta</td>
                        <td class="activo">@(transaccionesDia.TipoOperacionID == TipoOperacion.Ingreso ? transaccionesDia.Monto.ToString("N") : null)</td>
                        <td class="pasivo">@(transaccionesDia.TipoOperacionID == TipoOperacion.Gasto ? transaccionesDia.Monto.ToString("N") : null)</td>
                    </tr>
                }
            }

        </tbody>
    </table>
}

ManejadorDePresupuestos/ManejadorDePresupuestos/Views/Shared/_ResumenMontos.cshtml
@model ResumenMontosViewModel

<section>
    <div class="container-totales mb-3">
        <div>
            <div class="fw-bold">
                Depositos
            </div>
            <div class="activos">
                @Model.Ingresos.ToString("N")
            </div>
        </div>
        <div>
            <div class="fw-bold">
                Retiros
            </div>
            <div class="pasivos">
                @Model.Gastos.ToString("N")
            </div>
        </div>
        <div>
            <div class="fw-bold">
                Total
            </div>
            <div class="activos">
                @Model.Total.ToString("N")
            </div>
        </div>
    </div>
</section>